export enum PublishStatus {
  Live = "live",
  Draft = "draft",
  Unknown = "unknown",
}

export enum TabKey {
  Content = "content",
  Theme = "theme",
}

export enum ThemeActionType {
  FETCH_START = "FETCH_START",
  FETCH_SUCCESS = "FETCH_SUCCESS",
  FETCH_ERROR = "FETCH_ERROR",
  SAVE_START = "SAVE_START",
  SAVE_SUCCESS = "SAVE_SUCCESS",
  SAVE_ERROR = "SAVE_ERROR",
  SAVE_CONFLICT = "SAVE_CONFLICT",
  SET_THEME_COLOR = "SET_THEME_COLOR",
  APPLY_PRESET = "APPLY_PRESET",
  RESET = "RESET",
}

export enum ContentActionType {
  FETCH_START = "FETCH_START",
  FETCH_SUCCESS = "FETCH_SUCCESS",
  FETCH_ERROR = "FETCH_ERROR",
  SAVE_START = "SAVE_START",
  SAVE_SUCCESS = "SAVE_SUCCESS",
  SAVE_ERROR = "SAVE_ERROR",
  SAVE_CONFLICT = "SAVE_CONFLICT",
  SET_SECTION_CONTENT = "SET_SECTION_CONTENT",
  SET_ACTIVE_SECTION = "SET_ACTIVE_SECTION",
  IGNORE_LOAD_ERROR = "IGNORE_LOAD_ERROR",
  RESET = "RESET",
}

export enum GlobalCmsActionType {
  TOGGLE_PUBLISH_START = "TOGGLE_PUBLISH_START",
  TOGGLE_PUBLISH_SUCCESS = "TOGGLE_PUBLISH_SUCCESS",
  TOGGLE_PUBLISH_ERROR = "TOGGLE_PUBLISH_ERROR",
}
