export const SubscriptionText = {
  PAGE_TITLE: "Plan & Subscription Workspace",
  PAGE_DESCRIPTION: "Configure plan pricing tier options, access features, and manage active vendor subscription lifecycles.",
  SECTION_CMS_TITLE: "Plan Pricing & Features",
  SECTION_CMS_SUBTITLE: "Configure standard plans, pricing levels, and access features.",
  SECTION_LIFECYCLE_TITLE: "Active Vendor Subscriptions",
  SECTION_LIFECYCLE_SUBTITLE: "Track, upgrade, extend, or cancel vendor subscription periods.",
  
  SEARCH_PLACEHOLDER: "Search by company name or store link...",
  NEW_PLAN_PLACEHOLDER: "Plan name (e.g., starter, pro)...",
  FILTER_STATUS_LABEL: "Filter by Status",
  FILTER_ALL_STATUS: "All Statuses",
  
  TABLE_HEADERS: {
    COMPANY_NAME: "Company Name",
    DOMAIN: "Store Domain",
    CURRENT_PLAN: "Current Plan",
    STATUS: "Subscription Status",
    TRIAL_ENDS: "Trial Ends",
    PERIOD_ENDS: "Period Ends",
    DATE_CREATED: "Subscription Start Date",
    ACTIONS: "Actions",
  },
  
  STATUS_LABELS: {
    trial: "Trial Mode",
    active: "Active",
    expired: "Expired",
    cancelled: "Cancelled",
    grace_period: "Grace Period",
  },

  ACTIONS: {
    MANAGE: "Manage",
    VIEW: "View Details",
    REFRESH: "Refresh",
    SAVING: "Saving changes...",
    LOADING: "Loading data...",
    NO_DATA: "No vendor subscriptions found matching your filters.",
    EDIT_TITLE: "Manage Vendor Subscription",
    EDIT_DESC: "Upgrade or downgrade plan levels, adjust status, and change trial or billing cycle dates.",
    COMPANY_LABEL: "Company",
    DOMAIN_LABEL: "Store Domain",
    PLAN_LABEL: "Subscription Plan",
    STATUS_LABEL: "Subscription Status",
    TRIAL_START: "Trial Start Date & Time",
    TRIAL_END: "Trial End Date & Time",
    PERIOD_START: "Billing Cycle Start",
    PERIOD_END: "Billing Cycle End",
    GRACE_END: "Grace Period End Date & Time",
    CANCELLED_AT: "Cancellation Date & Time",
    SAVE_BTN: "Save Changes",
    CANCEL_BTN: "Cancel",
    SUCCESS_UPDATE: "Vendor subscription updated successfully!",
    FAILED_UPDATE: "Failed to update vendor subscription.",
    FETCH_ERROR: "Failed to load vendor subscriptions.",
    FEATURE_KEY_LABEL: "Feature Name / Identifier",
    FEATURE_KEY_PLACEHOLDER: "e.g., maximum-products-allowed",
    PREVIEW_TITLE: "Storefront Card Preview (Approximate)",
  }
};
