export const UiText = {
  TITLE: "Storefront CMS Manager",
  SUBTITLE: "Manage all storefront content dynamically",
  SAVING: "Saving...",
  SAVE_CHANGES: "Save Changes",
  RESET: "Reset",
  SAVE_CONFIGURATION: "Save Configuration",
  PAGE_SECTION: "Page / Section",
  LANGUAGE: "Language",
  ENGLISH: "English",
  ESPANOL: "Español",
  PREVIEW: "Preview",
  UPLOADING: "Uploading...",
  UPLOAD_IMAGE: "Upload Image",
  CLOUDINARY_ATTACHED: "✓ Cloudinary Image Attached",
  SIZE_LIMIT_ERROR: "File size must be under 5MB.",
  UPLOAD_FAILED: "Upload failed. Try again.",
  REMOVE_IMAGE: "Remove",
  AUTO_SAVED: "✓ Auto-saved",
  DELETE_FAILED: "Old image removal from cloud failed (non-critical).",
  FILTER_TAGS: "Filter tags…",
  LOADING_PRODUCTS: "Loading products from your store…",
  NO_MATCHING_TAGS: "No matching tags. Try a different search.",
  NO_TAGS_SELECTED: "No tags selected — all products will show.",
  SELECTED: "Selected",
  CLEAR_ALL: "Clear all",
  LOADING_PREVIEW: "Loading product preview...",
  SAVE_SUCCESS: "Saved! Storefront will reflect changes on next page load.",
  SAVE_FAILED_PREFIX: "Save failed: ",
  TRY_AGAIN: "Try again.",
  NO_SLIDES:
    "No slides yet. Click Add Slide to add hero carousel images. Each slide can link to a product search on the shop page.",
  KEY_STATS: "Key Stats (Max 3 Recommended)",
  NO_STATS:
    "No stats added. Default promise stats will be shown on the storefront.",
  VIDEO_OVERLAY_CONTENT: "Video Background Overlay Content",
  VISUAL_PREVIEW_TITLE: "Visual Preview & Placement",
  VISUAL_PREVIEW_INSTRUCTIONS:
    "1. Select a hotspot card from the list below (it will highlight in purple). 2. Click anywhere on the image preview to position the selected hotspot. If no card is selected, clicking will add a new hotspot.",
  LOOKBOOK_MAP_ALT: "Lookbook Interactive Map",
  UPLOAD_LOOKBOOK_PROMPT:
    "Upload a Main Lookbook Image to enable visual hotspot placement.",
  NO_HOTSPOTS:
    "No hotspots added. Press Add Hotspot or click the image above to place interactive tags.",
  NO_LINKS: "No links yet. Click Add Link.",
  LINK: "Link",
  SHOP_NOW: "Shop Now",
  NO_POLICIES: "No policies match your search.",
  NO_POLICIES_FOUND: "No policies found. Create your first one.",
  LOADING_POLICIES: "Loading policies...",
  DELETE_POLICY_TITLE: "Delete Policy?",
  DELETE_POLICY_MSG:
    "This action cannot be undone. Are you sure you want to delete this policy?",
  YES_DELETE: "Yes, Delete",
  FAILED_LOAD_POLICIES: "Failed to load policies.",
  PRODUCT_POLICIES_TITLE: "Product Policies",
  PRODUCT_POLICIES_SUBTITLE: "Manage warranties, guarantees, and return rules.",
  COVERAGE_MAP: "Coverage Map",
  ASSIGN_POLICIES: "Assign Policies",
  CREATE_POLICY: "Create Policy",
  TOTAL_POLICIES: "Total Policies",
  ACTIVE: "Active",
  INACTIVE: "Inactive",
  WITH_DURATION: "With Duration",
  SEARCH_POLICIES_PLACEHOLDER: "Search policies...",
  VIEW_COVERAGE: "View coverage",
  EDIT: "Edit",
  DELETE: "Delete",
  COVERAGE: "Coverage",
  TABLE_HEADER_NAME: "Policy Name",
  TABLE_HEADER_TYPE: "Type",
  TABLE_HEADER_DURATION: "Duration",
  TABLE_HEADER_STATUS: "Status",
  TABLE_HEADER_COVERAGE: "Coverage",
  TABLE_HEADER_ACTIONS: "Actions",
  SELECT_PRODUCT: "-- Select Product --",
  ADD_PRODUCT_TO_CURATED: "-- Add Product to Curated List --",
  CUSTOMER_TESTIMONIALS: "Customer Testimonials",
  RATING_1_5: "Rating (1-5)",
  TRUST_BADGE_STRIP: "Trust Badge Strip",
  SELECT_ICON: "Select Icon",
  POLICY_NOT_FOUND: "Policy not found.",
  POLICY_LOAD_EDIT_ERROR: "Failed to load policy for editing.",
  POLICY_SAVE_ERROR: "Failed to save policy.",
  EDIT_POLICY: "Edit Product Policy",
  CREATE_NEW_POLICY: "Create New Product Policy",
  POLICY_SUBTITLE:
    "Define warranty or return rules to assign to products/categories.",
  LOADING_POLICY_DATA: "Loading policy data...",
  BASIC_DETAILS: "Basic Details",
  POLICY_NAME: "Policy Name",
  POLICY_TYPE: "Policy Type",
  SELECT_TYPE: "Select Type",
  DURATION_VALUE: "Duration Value",
  DURATION_UNIT: "Duration Unit",
  COVERAGE_CLAIMS_CONFIG: "Coverage & Claims Configuration",
  COVERAGE_DESC: "Coverage Description",
  COVERAGE_PLACEHOLDER: "What does this cover?",
  EXCLUSIONS: "Exclusions",
  EXCLUSIONS_PLACEHOLDER: "What is explicitly excluded?",
  SERVICE_PROVIDER: "Service Provider",
  CLAIM_EMAIL: "Claim Email",
  CLAIM_PHONE: "Claim Phone",
  GENERATES_PDF: "Generates Warranty PDF/Document",
  POLICY_IS_ACTIVE: "Policy is Active",
  CANCEL: "Cancel",
  UPDATE_POLICY: "Update Policy",
  SAVE_POLICY: "Save Policy",
  ASSIGN: {
    LOAD_ERROR:
      "Failed to load policies, categories, or products. Please try again later.",
    ASSIGN_ERROR: "Failed to assign policy.",
    TITLE: "Assign Product Policy",
    SUBTITLE:
      "Apply rules to an entire category or override them for a specific product.",
    WHERE_APPLY: "Where should this policy apply?",
    CATEGORY_DEFAULT: "Category Default",
    PRODUCT_OVERRIDE: "Specific Product Override",
    SELECT_POLICY: "Select Policy to Assign",
    CHOOSE_POLICY: "-- Choose Policy --",
    SELECT_POLICY_REQUIRED: "Please select a policy",
    SELECT_CATEGORY: "Select Category",
    SELECT_PRODUCT: "Select Product",
    CHOOSE_CATEGORY_PLACEHOLDER: "-- Choose Category --",
    CHOOSE_PRODUCT_PLACEHOLDER: "-- Choose Product --",
    SELECT_TARGET_REQUIRED: "Please select a target",
    PRIORITY_LEVEL: "Priority Level",
    PRIORITY_DESC: "(lower = higher priority)",
    ASSIGNING: "Assigning...",
    ASSIGN_POLICY: "Assign Policy",
    LOADING: "Loading...",
  },
  COVERAGE_MAP_PAGE: {
    BACK_TO_POLICIES: "Back to Policies",
    TITLE: "Policy Coverage Map",
    SUBTITLE: "See which categories and products each policy covers",
    CATEGORY_LINKS: "Category Links",
    PRODUCT_OVERRIDES: "Product Overrides",
    UNASSIGNED: "Unassigned",
    SEARCH_PLACEHOLDER: "Search policies, categories or products...",
    ALL_TYPES: "All Types",
    NO_MATCHES: "No policies match your filters.",
    ASSIGN_POLICIES: "Assign policies",
    INACTIVE: "Inactive",
    GENERATES_PDF: "📄 Generates PDF",
    DURATION_PREFIX: "Duration: ",
    CATEGORY_SINGULAR: "category",
    CATEGORY_PLURAL: "categories",
    PRODUCT_SINGULAR: "product",
    PRODUCT_PLURAL: "products",
    FULL_DETAIL: "Full Detail",
    CATEGORIES_HEADER: "Categories",
    NO_CATEGORIES: "No categories assigned",
    PRODUCT_OVERRIDES_HEADER: "Product Overrides",
    NO_OVERRIDES: "No product overrides",
    MORE: "more",
    NOT_ASSIGNED_WARNING:
      "This policy is not assigned to any category or product yet.",
    ASSIGN_NOW: "Assign now",
  },
  COVERAGE_DETAIL_PAGE: {
    NOT_FOUND: "Policy coverage details not found.",
    LOAD_ERROR: "Failed to load policy coverage details.",
    ERROR_FALLBACK: "Something went wrong",
    BACK_TO_MAP: "Back to Coverage Map",
    MANAGE_ASSIGNMENTS: "Manage Assignments",
    EDIT_POLICY: "Edit Policy",
    POLICY_CONFIG: "Policy Configuration",
    DURATION: "Duration",
    LIFETIME_NO_EXPIRY: "Lifetime / No Expiry",
    STATUS: "Status",
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    DOCUMENTATION: "Documentation",
    GENERATES_PDF: "Generates PDF for Orders",
    NO_PDF_GENERATED: "No PDF Generated",
    LINKED_CATEGORIES: "Linked Categories",
    ASSIGNED: "Assigned",
    NOT_ASSIGNED: "Not assigned to any categories.",
    INHERITED_COVERAGE: "Inherited Product Coverage",
    INHERITED_SUBTITLE:
      "Products automatically covered because they belong to the linked categories above.",
    COVERED: "Covered",
    NO_INHERITED: "No products found in the assigned categories.",
    VIA_PREFIX: "Via: ",
    DIRECT_OVERRIDES: "Direct Product Overrides",
    OVERRIDES: "Overrides",
    NO_DIRECT_OVERRIDES: "No direct overrides applied.",
    DIRECT_OVERRIDE_BADGE: "Direct Override",
  },
  DASHBOARD: {
    INVOICES_NOT_FOUND: "No generated invoices found for these orders yet.",
    INVOICES_FAILED: "Failed to download invoices.",
    TOTAL_REVENUE: "Total Revenue",
    VS_LAST_MONTH: "vs last month",
    PENDING_ORDERS: "Pending Orders",
    IMMEDIATE_SHIPPING_REQUIRED: "Requires immediate shipping",
    ACTIVE_PRODUCTS: "Active Products",
    LOW_STOCK_WARNING: "products low on stock",
    REVENUE_OVERVIEW: "Revenue Overview",
    LAST_30_DAYS: "Last 30 Days",
    NOT_ENOUGH_DATA: "Not enough data to display chart.",
    TOP_PERFORMING_PRODUCTS: "Top Performing Products",
    RECENT_ORDERS: "Recent Orders",
    PRINT_INVOICES: "Print Invoices",
    DOWNLOADING: "Downloading...",
    SELECT_STATUS: "Select Status",
    VIEW_ALL: "View All",
    NO_ORDERS_FOUND: "No orders found.",
    NO_SALES_DATA: "No sales data available yet.",
    VIEW_ARROW: "View →",
    STATUS_LABELS: {
      PENDING: "Pending",
      PROCESSING: "Processing",
      SHIPPED: "Shipped",
      DELIVERED: "Delivered",
      CANCELLED: "Cancelled",
      RETURNED: "Returned",
      REFUNDED: "Refunded",
      REPLACED: "Replaced",
      DRAFTING: "Drafting",
      AWB_ASSIGNED: "AWB Assigned",
      IN_TRANSIT: "In Transit",
      OUT_FOR_DELIVERY: "Out For Delivery",
      OUT_FOR_DELIVERY_EXCEPTION: "Out For Delivery Exception",
      UNDELIVERED: "Undelivered",
      RTO: "RTO",
      FAILED: "Failed",
      ACTIVE: "Active",
      RETURN: "Return",
      REPLACEMENT: "Replacement",
    }
  },
  LAYOUTS: {
    CENTER_OVERLAY: "Centered Text Overlay",
    LEFT_SPLIT: "Text Left, Image Right (Split)",
    RIGHT_SPLIT: "Image Left, Text Right (Split)",
  },
  BG_STYLES: {
    GRADIENT: "Automatic Edge Gradient",
    SOLID: "Automatic Edge Solid Color",
    CUSTOM: "Custom Color (Pick Below)",
  },
  BANNER_TYPES: {
    CAROUSEL: "Image Carousel Slider",
    VIDEO: "Video Background Banner",
  },
  CURATION_TYPES: {
    TRENDING: "Trending Masterpieces",
    NEW_ARRIVALS: "New Arrivals",
    CURATED: "Curated Custom Products (IDs Below)",
  },
  CONTACT_TYPES: {
    PHONE: "Phone",
    EMAIL: "Email",
    ADDRESS: "Address",
    OTHER: "Other",
  },
  ICONS: {
    SHIPPING: "Delivery / Shipping",
    SECURITY: "Shield / Security",
    QUALITY: "Award / Quality",
    SUPPORT: "Headphones / Support",
    DEFAULT: "Heart / Default",
  },
  DURATION_UNITS: {
    DAYS: "Days",
    MONTHS: "Months",
    YEARS: "Years",
    LIFETIME: "Lifetime",
  },
  ORDERS: {
    TITLE: "Orders",
    PRINT_INVOICES: "Print Invoices",
    DOWNLOADING: "Downloading...",
    ALL: "All",
    PENDING: "Pending",
    PROCESSING: "Processing",
    SHIPPED: "Shipped",
    DELIVERED: "Delivered",
    CANCELLED: "Cancelled",
    NEWEST_FIRST: "Newest First",
    OLDEST_FIRST: "Oldest First",
    NO_ORDERS: "No orders found.",
    VIEW_ARROW: "View →",
    NO_INVOICES_WARNING: "No generated invoices found for these orders yet.",
    FAILED_DOWNLOAD_INVOICES: "Failed to download invoices.",
    ACTIVE: "Active",
    NA: "N/A",
    TABLE_HEADERS: {
      ORDER_ID: "Order ID",
      TOTAL_AMOUNT: "Total Amount",
      QTY: "Qty",
      STATUS: "Status",
      CUSTOMER: "Customer",
      PAYMENT: "Payment",
      LOCATION: "Location",
      DATE: "Date",
      ACTIONS: "Actions",
    },
  },
  ORDER_DETAILS: {
    LOADING: "Loading order…",
    BACK_TO_ORDERS: "Back to Orders",
    TITLE: "Order Details",
    VIEW_INVOICE: "View Invoice",
    MULTI_WAREHOUSE_ALERT: "Multiple warehouses detected.",
    MULTI_WAREHOUSE_DESC:
      "Order status and tracking URLs are managed individually per item below.",
    ITEMS_COUNT: "Items ({count})",
    QTY: "Qty:",
    TOTAL: "Total:",
    STATUS: "Status",
    CANCEL_THIS_ITEM: "Cancel this item",
    PROCESS_RETURN_ARROW: "Process Return →",
    REASON: "Reason:",
    NOTE: "Note:",
    CANCELLATION_DETAILS: "Cancellation Details",
    BY: "By",
    REFUND_INFO: "Refund Information",
    AMOUNT: "Amount:",
    SHIPPING_ADDRESS: "Shipping Address",
    CUSTOMER: "Customer",
    ORDER_SUMMARY: "Order Summary",
    ORDER_DATE: "Order date",
    PAYMENT: "Payment",
    FULFILLMENT: "Fulfillment",
    ORDER_STATUS: "Order Status",
    TRACKING_URL: "Tracking URL",
    TRACKING_URL_ONLY_AFTER_SHIPPING: "Tracking URL (Only after shipping)",
    MULTI_WAREHOUSE_FULFILLMENT_DESC:
      "Status and tracking are managed per item since this order ships from multiple warehouses. See the items panel on the left.",
    STATUS_LABELS: {
      PENDING: "Pending",
      PROCESSING: "Processing",
      SHIPPED: "Shipped",
      DELIVERED: "Delivered",
      CANCELLED: "Cancelled",
    },
    SAVING: "Saving…",
    SAVE: "Save",
    CANCEL: "Cancel",
    EDIT: "Edit",
    VIEW_TRACKING: "View tracking",
    UPDATE_URL: "Update URL",
    ADD_TRACKING_URL: "Add tracking URL",
    TRACKING_PLACEHOLDER: "https://track.carrier.com/…",
    CANCEL_ITEM_TITLE: "Cancel item",
    CANT_BE_UNDONE: "This action cannot be undone.",
    CANCELLATION_REASON_PLACEHOLDER: "Reason for cancellation…",
    CONFIRM_CANCELLATION: "Confirm cancellation",
    CANCELLING: "Cancelling…",
    KEEP_ITEM: "Keep item",
    REQUEST_SUFFIX: "Request",
  },
  CUSTOMER_ORDERS: {
    MY_ORDERS: "My Orders",
    STATUS_LABELS: {
      SHIPPING: "shipping",
      PROCESSING: "Not Shipped Yet",
      DELIVERED: "Delivered",
      CANCELLED: "Cancelled",
      RETURNS: "Returns & Replacements",
    },
  },
  BACK_ORDERS: {
    TITLE: "Back Orders",
    LOAD_ERROR: "Failed to load return requests",
    NO_ORDERS: "No back orders found.",
    NA: "N/A",
    SKU_PREFIX: "SKU: ",
    QTY_PREFIX: "Qty: ",
    REVIEW: "Review →",
    ALL_STATUS: "All Status",
    ALL_TYPES: "All Types",
    STATUS_LABELS: {
      PENDING: "Pending",
      APPROVED: "Approved",
      REJECTED: "Rejected",
      PROCESSING: "Processing",
    },
    TYPE_LABELS: {
      RETURN: "Return",
      REPLACEMENT: "Replacement",
    },
    TABLE_HEADERS: {
      REQUEST_ID: "Request ID",
      TYPE: "Type",
      PRODUCT: "Product",
      PRICE: "Price",
      REASON: "Reason",
      STATUS: "Status",
      LOCATION: "Location",
      DATE: "Date",
      ACTIONS: "Actions",
    },
  },
  BACK_ORDER_DETAILS: {
    BACK: "Back to Back Orders",
    PRODUCT: "Product",
    UNIT_PRICE: "Unit Price",
    QTY: "Qty",
    ORDER_STATUS: "Order Status",
    ORDER_ID_PREFIX: "Order ID: ",
    REQUEST_DETAILS: "Request Details",
    REQUEST_TYPE: "Request Type",
    SUBMITTED: "Submitted",
    LAST_UPDATED: "Last Updated",
    TRACKING_ID: "Tracking ID",
    REASON: "Reason",
    CUSTOMER_NOTE: "Customer Note",
    STORE_OWNER_NOTE: "Store Owner Note",
    EVIDENCE_PHOTOS: "Evidence Photos",
    IMAGE_SINGULAR: "image",
    IMAGE_PLURAL: "images",
    NO_EVIDENCE: "No evidence photos provided.",
    CUSTOMER: "Customer",
    NO_PHONE: "No phone",
    DELIVERY_ADDRESS: "Delivery Address",
    NO_ADDRESS: "No address on file.",
    RESOLUTION: "Resolution",
    UPDATE_STATUS: "Update Status",
    TRACKING_URL: "Tracking URL",
    TRACKING_URL_PLACEHOLDER: "Enter tracking URL",
    INTERNAL_NOTE: "Internal Note",
    REQUIRED: "*required",
    NOTE_REQ_PLACEHOLDER: "Required: provide reason...",
    NOTE_OPT_PLACEHOLDER: "Optional note for customer or records...",
    CONFIRM_UPDATE: "Confirm Update",
    SAVING: "Saving...",
    NO_CHANGES: "No changes to save.",
    LOAD_ERROR: "Failed to load request details",
    STATUS_REQUIRED: "Please select a status",
    NOTE_REQUIRED: "A note is required for rejections or QC failures",
    UPDATE_SUCCESS: "Status updated successfully",
    UPDATE_FAILED: "Update failed",
    NA: "N/A",
    STATUS_LABELS: {
      PENDING: "Pending",
      APPROVED: "Approved",
      REJECTED: "Rejected",
      PROCESSING: "Processing",
      QC_FAILED: "QC Failed",
    },
    TYPE_LABELS: {
      RETURN: "Return",
      REPLACEMENT: "Replacement",
    },
  },
};

export const SHIPPING_TEXT = {
  PAGE_TITLE: "Shipping & Logistics Settings",
  PAGE_DESC:
    "Configure how shipping costs are calculated on your storefront and manage fulfillment api credentials.",
  LOGISTICS_MODE_TITLE: "Fulfillment Logistics Mode",
  LOGISTICS_MODE_DESC:
    "Determine whether orders are fulfilled under the central platform account (Platform Proxy Mode) or using your own Shiprocket credentials.",
  PLATFORM_PROXY_LABEL: "Platform Proxy Mode",
  PLATFORM_PROXY_DESC:
    "Fulfillment goes through the Platform's Master Shiprocket wallet. Shipping costs are recovered via gateway splits.",
  STANDALONE_LABEL: "Standalone Mode (BYO Credentials)",
  STANDALONE_DESC:
    "Fulfilment runs directly on your own Shiprocket account. Enter your verified email and password below.",
  CREDS_TITLE: "Shiprocket Account Credentials",
  CREDS_DESC:
    "Provide your API logins. These will be encrypted securely using AES-256-GCM and will never be exposed.",
  API_EMAIL_LABEL: "Shiprocket API Email",
  API_EMAIL_PLACEHOLDER: "Enter Shiprocket Account Email",
  API_PASSWORD_LABEL: "Shiprocket API Password",
  API_PASSWORD_PLACEHOLDER: "Enter Shiprocket Account Password",
  COST_CALC_TITLE: "Storefront Delivery Cost Calculations",
  COST_CALC_DESC:
    "Configure how standard courier shipping is charged to customers on your storefront.",
  FLAT_RATE_LABEL: "Standard Flat Rate",
  FLAT_RATE_DESC:
    "Charge a fixed shipping amount for all orders below the threshold.",
  DYNAMIC_RATE_LABEL: "Dynamic Customer Rate",
  DYNAMIC_RATE_DESC:
    "Automatically calculate and charge live shipping rates using Shiprocket.",
  STD_SHIPPING_LABEL: "Standard Shipping Flat Rate (₹)",
  SAVED_TEXT: "Saved",
  EDIT_TEXT: "Edit",
  CURRENCY_SYMBOL: "₹",
  FLAT_FEE_HINT:
    "Flat shipping fee charged if order amount does not reach the free delivery threshold.",
  FREE_SHIPPING_LABEL: "Enable Free Shipping Rule",
  FREE_SHIPPING_HINT: "Unlock free delivery above a cart value threshold.",
  FREE_SHIPPING_THRESHOLD_LABEL: "Free Shipping Order Threshold Value (₹)",
  FREE_SHIPPING_ACTIVE_HINT:
    "Orders at or above this cart total amount will enjoy free delivery.",
  FREE_SHIPPING_INACTIVE_HINT:
    "Enable the Free Shipping Rule above to configure the threshold value.",
  BTN_SAVE: "Save Configuration",
  DEFAULT_FREE_DELIVERY_THRESHOLD: "0.00",
  DEFAULT_STANDARD_DELIVERY_CHARGE: "50.00",
  SUCCESS_MSG: "Shipping settings saved successfully.",
  ERROR_MSG: "Failed to update shipping settings",
  SAVE_TIMEOUT_MS: 3000,
  API_SECRET_MASK: "********",
};
