export enum HelpArticlesErrorKeyEnum {
  FAILED_TO_FETCH_HELP_ARTICLES = 'Failed to fetch help articles',
  HELP_ARTICLE_WITH_ID_ID_NOT_FOUND = 'Help article with ID ${id} not found',
  FAILED_TO_FETCH_HELP_ARTICLE = 'FAILED TO FETCH HELP ARTICLE',
  FAILED_TO_CREATE_HELP_ARTICLE = 'FAILED TO CREATE HELP ARTICLE',
  FAILED_TO_SUBMIT_VOTE = 'FAILED TO SUBMIT VOTE',
}
