export enum ProductsErrorKeyEnum {
  FAILED_TO_COUNT_PRODUCTS = 'Failed to count products',
  FAILED_TO_FETCH_PRODUCTS = 'Failed to fetch products',
  FAILED_TO_FETCH_SUGGESTIONS = 'Failed to fetch suggestions',
  FAILED_TO_FETCH_PRODUCT = 'Failed to fetch product',
  FAILED_TO_FETCH_CATEGORY = 'Failed to fetch category',
  PRODUCT_NOT_FOUND = 'Product not found',
  FAILED_TO_CHECK_PRODUCT_VARIANT_EXISTENCE = 'Failed to check product variant existence',
  PRODUCT_VARIANT_NOT_FOUND = 'Product variant not found',
  FAILED_TO_FETCH_ACTIVE_PRODUCTS = 'Failed to fetch active products',

  FAILED_TO_FETCH_HOMEPAGE_PRODUCTS = 'Failed to fetch homepage products',
  FAILED_TO_CREATE_PRODUCT_VARIANT = 'Failed to create product variant',
  FAILED_TO_CREATE_PRODUCT_TAX_MAPPING = 'Failed to create product tax mapping',
  FAILED_TO_REGISTER_VENDOR = 'Failed to register vendor',
  PRODUCT_VARIANT_ID_IS_REQUIRED = 'Product Variant ID is required',
  FAILED_TO_FETCH_PRODUCT_VARIANT = 'Failed to fetch product variant',
  PRODUCT_ID_NOT_FOUND_FOR_THE_GIVEN_VARIANT = 'Product ID not found for the given variant',
  PRODUCT_DATA_NOT_VALID = 'Product data not valid',
  FAILED_TO_UPDATE_PRODUCT = 'Failed to update product',
  FAILED_TO_INSERT_PRODUCT_IMAGES = 'Failed to insert product images',
  FAILED_TO_FETCH_IMAGE_URLS_FOR_DELETION = 'Failed to fetch image URLs for deletion',
  FAILED_TO_DELETE_PRODUCT_IMAGE = 'Failed to delete product image',
  FAILED_TO_UPDATE_PRODUCT_VARIANT = 'Failed to update product variant',
  PRODUCT_ID_IS_REQUIRED = 'Product ID is required',
  FAILED_TO_DELETE_PRODUCT = 'Failed to delete product',
  CATEGORY_ID_IS_REQUIRED = 'Category ID is required',
  FAILED_TO_UPDATE_PRODUCT_CATEGORY = 'Failed to update product category',
  PRODUCT_IDS_ARE_REQUIRED = 'Product IDs are required',
  FAILED_TO_DELETE_SELECTED_PRODUCTS = 'Failed to delete  selected products',
  VARIANT_ID_IS_REQUIRED = 'Variant ID is required',
  FAILED_TO_DELETE_PRODUCT_VARIANT = 'Failed to delete product variant',
  VARIANT_IDS_ARE_REQUIRED = 'Variant IDs are required',
  IMAGE_ID_IS_REQUIRED = 'Image ID is required',
}
