export enum ShippingErrorKeyEnum {
  COMPANY_WITH_DOMAIN_DOMAIN_NOT_FOUND = 'Company with domain ${domain} not found',
  ORDER_NOT_FOUND = 'ORDER NOT FOUND',
  FAILED_TO_UPDATE_TRACKING_URL = 'FAILED TO UPDATE TRACKING URL',
  ERROR_OCCURRED_WHILE_FETCHING_ORDER = 'ERROR OCCURRED WHILE FETCHING ORDER',
  SHIPPING_DETAILS_NOT_FOUND = 'SHIPPING DETAILS NOT FOUND',
  ERROR_OCCURRED_WHILE_FETCHING_TRACKING_INFORMATION = 'ERROR OCCURRED WHILE FETCHING TRACKING INFORMATION',
}
