export enum InvoiceErrorKeyEnum {
  FAILED_TO_FETCH_ORDER_ORDERID = 'Failed to fetch order ${orderId}.',
  ERROR_FETCHING_COMPANY_COMPLIANCE = 'ERROR FETCHING COMPANY COMPLIANCE',
  COUNTRY_COMPLIANCE_CONFIG_NOT_FOUND = 'COUNTRY COMPLIANCE CONFIG NOT FOUND',
  GST_FIELD_CONFIG_MISSING = 'GST FIELD CONFIG MISSING',
  ERROR_FETCHING_VENDOR_GST_NUMBER = 'ERROR FETCHING VENDOR GST NUMBER',
  VENDOR_GST_NUMBER_IS_MISSING = 'VENDOR GST NUMBER IS MISSING',
  NO_WAREHOUSES_FOUND = 'NO WAREHOUSES FOUND',
}
