export enum PromotionsErrorKeyEnum {
  FAILED_TO_RESOLVE_COMPANY_ID = 'Failed to resolve company id',
  PERCENTAGE_OFF_REQUIRES_VALUE_NUMBER_1_100 = 'percentage_off requires value: number (1–100)',
  FIXED_AMOUNT_REQUIRES_VALUE_POSITIVE_NUMBER = 'fixed_amount requires value: positive number',
  BUY_X_GET_Y_REQUIRES_BUY_QTY_GET_QTY_GET_PRODUCT_VARIANT_ID = 'buy_x_get_y requires buy_qty, get_qty, get_product_variant_id',
  FREE_SHIPPING_REQUIRES_MAX_SHIPPING_WAIVED_NUMBER = 'free_shipping requires max_shipping_waived: number',
  TIERED_DISCOUNT_REQUIRES_TIERS_ARRAY = 'tiered_discount requires tiers array',
  BUNDLE_DEAL_REQUIRES_PRODUCT_VARIANT_IDS_AND_BUNDLE_PRICE = 'bundle_deal requires product_variant_ids[] and bundle_price',
  FAILED_TO_FETCH_PROMOTIONS = 'Failed to fetch promotions',
  FAILED_TO_LIST_PROMOTIONS = 'Failed to list promotions',
  FAILED_TO_FETCH_PROMOTION_OPTIONS = 'Failed to fetch promotion options',
  FAILED_TO_LIST_PROMOTION_OPTIONS = 'Failed to list promotion options',
  FAILED_TO_FETCH_PROMOTION = 'Failed to fetch promotion',
  PROMOTION_NOT_FOUND = 'Promotion not found',
  FAILED_TO_GET_PROMOTION = 'Failed to get promotion',
  FAILED_TO_FETCH_PROMOTION_ANALYTICS = 'Failed to fetch promotion analytics',
  FAILED_TO_GET_PROMOTION_ANALYTICS = 'Failed to get promotion analytics',
  FAILED_TO_CREATE_PROMOTION = 'Failed to create promotion',
  FAILED_TO_INSERT_PROMOTION_RULES = 'Failed to insert promotion rules',
  FAILED_TO_INSERT_PROMOTION_TARGETS = 'Failed to insert promotion targets',
  FAILED_TO_CREATE_PROMOTION_TRANSACTION = 'Failed to create promotion transaction',
  FAILED_TO_FETCH_EXISTING_PROMOTION = 'Failed to fetch existing promotion',
  FAILED_TO_UPDATE_PROMOTION = 'Failed to update promotion',
  FAILED_TO_DELETE_OLD_PROMOTION_RULES = 'Failed to delete old promotion rules',
  FAILED_TO_DELETE_OLD_PROMOTION_TARGETS = 'Failed to delete old promotion targets',
  FAILED_TO_UPDATE_PROMOTION_TRANSACTION = 'Failed to update promotion transaction',
  FAILED_TO_DEACTIVATE_PROMOTION = 'Failed to deactivate promotion',
}
