import { CountryCompliance } from './Types/index.type';

export interface StateCode {
  state: string;
  code: string;
}

export const STATE_CODE: StateCode[] = [
  { state: 'Jammu and Kashmir', code: '01' },
  { state: 'Himachal Pradesh', code: '02' },
  { state: 'Punjab', code: '03' },
  { state: 'Chandigarh', code: '04' },
  { state: 'Uttarakhand', code: '05' },
  { state: 'Haryana', code: '06' },
  { state: 'Delhi', code: '07' },
  { state: 'Rajasthan', code: '08' },
  { state: 'Uttar Pradesh', code: '09' },
  { state: 'Bihar', code: '10' },
  { state: 'Sikkim', code: '11' },
  { state: 'Arunachal Pradesh', code: '12' },
  { state: 'Nagaland', code: '13' },
  { state: 'Manipur', code: '14' },
  { state: 'Mizoram', code: '15' },
  { state: 'Tripura', code: '16' },
  { state: 'Meghalaya', code: '17' },
  { state: 'Assam', code: '18' },
  { state: 'West Bengal', code: '19' },
  { state: 'Jharkhand', code: '20' },
  { state: 'Odisha', code: '21' },
  { state: 'Chhattisgarh', code: '22' },
  { state: 'Madhya Pradesh', code: '23' },
  { state: 'Gujarat', code: '24' },
  { state: 'Dadra and Nagar Haveli and Daman and Diu', code: '26' }, // Merged UT code
  { state: 'Maharashtra', code: '27' },
  { state: 'Karnataka', code: '29' }, // Fixed mapping
  { state: 'Goa', code: '30' },
  { state: 'Lakshadweep', code: '31' },
  { state: 'Kerala', code: '32' },
  { state: 'Tamil Nadu', code: '33' },
  { state: 'Puducherry', code: '34' },
  { state: 'Andaman and Nicobar Islands', code: '35' },
  { state: 'Telangana', code: '36' },
  { state: 'Andhra Pradesh', code: '37' }, // Standard post-division code
  { state: 'Ladakh', code: '38' }, // Newest territory code
  { state: 'Other Territory', code: '97' },
  { state: 'Centre Jurisdiction', code: '99' }, // Used for specific administrative reporting
];
export const getStateByCode = (code: string) => {
  return STATE_CODE.find((item) => item.code === code);
};

export const getCodeByState = (state: string) => {
  return STATE_CODE.find(
    (item) => item.state.toLowerCase() === state.toLowerCase(),
  );
};

export const COUNTRIES_COMPLIANCE: CountryCompliance[] = [
  {
    country_code: 'AE',
    country_name: 'United Arab Emirates',
    taxConfig: {
      currency: 'AED',
      hasVat: true,
      vatRate: 5,
    },
    fields: [
      {
        value: 'trn',
        label: 'Tax Registration Number (TRN)',
        placeholder: 'TRN',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Required for VAT invoices.',
      },
      {
        value: 'trade_license',
        label: 'Trade License Number',
        placeholder: 'Trade License',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Business registration.',
      },
    ],
  },

  {
    country_code: 'IN',
    country_name: 'India',

    taxConfig: {
      currency: 'INR',
      hasVat: true,
    },

    fields: [
      {
        value: 'gstin',
        label: 'GSTIN',
        placeholder: '24ABCDE1234F1Z5',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText:
          '15-digit GST number. First 2 digits automatically determine GST state. Used for CGST/SGST or IGST calculation.',
      },

      {
        value: 'pan',
        label: 'PAN',
        placeholder: 'ABCDE1234F',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText:
          'Permanent Account Number linked with GST and business entity.',
      },

      {
        value: 'fssai',
        label: 'FSSAI License Number',
        placeholder: '12345678901234',
        required: false,
        requiredForSelling: false,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText:
          'Required when selling food, beverages, packaged food, supplements or edible products. Can be printed on invoice and product packaging.',
      },

      {
        value: 'msme',
        label: 'MSME / UDYAM Registration',
        placeholder: 'UDYAM-GJ-00-0000000',
        required: false,
        requiredForSelling: false,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText:
          'Optional. Helps with MSME compliance, tenders, subsidies and vendor trust.',
      },

      {
        value: 'dpiit',
        label: 'DPIIT Startup Recognition',
        placeholder: 'DIPP123456',
        required: false,
        requiredForSelling: false,
        showOnInvoice: false,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText:
          'Optional for recognized startups. Useful for grants, startup benefits and compliance.',
      },

      {
        value: 'iec',
        label: 'IEC (Import Export Code)',
        placeholder: 'ABCDE1234F',
        required: false,
        requiredForSelling: false,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText:
          'Required for import/export transactions and international shipping from India.',
      },

      {
        value: 'cin_llpin',
        label: 'CIN / LLPIN',
        placeholder: 'U12345GJ2026PTC000001',
        required: false,
        requiredForSelling: false,
        showOnInvoice: false,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Company or LLP registration number issued by MCA.',
      },

      {
        value: 'trade_license',
        label: 'Trade License',
        placeholder: 'Municipal Trade License',
        required: false,
        requiredForSelling: false,
        showOnInvoice: false,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText:
          'Local municipal business license if required by city/state.',
      },
    ],
  },
  {
    country_code: 'GB',
    country_name: 'United Kingdom',
    taxConfig: {
      currency: 'GBP',
      hasVat: true,
      vatRate: 20,
    },
    fields: [
      {
        value: 'vat_number',
        label: 'VAT Number',
        placeholder: 'GB VAT Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'VAT registration.',
      },
      {
        value: 'company_number',
        label: 'Company Registration Number',
        placeholder: 'Company Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Companies House registration.',
      },
    ],
  },

  {
    country_code: 'AU',
    country_name: 'Australia',
    taxConfig: {
      currency: 'AUD',
      hasVat: true,
      vatRate: 10,
    },
    fields: [
      {
        value: 'abn',
        label: 'ABN',
        placeholder: 'Australian Business Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Business registration.',
      },
      {
        value: 'gst_registration',
        label: 'GST Registration',
        placeholder: 'GST Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'GST billing.',
      },
    ],
  },

  {
    country_code: 'NZ',
    country_name: 'New Zealand',
    taxConfig: {
      currency: 'NZD',
      hasVat: true,
      vatRate: 15,
    },
    fields: [
      {
        value: 'ird_number',
        label: 'IRD Number',
        placeholder: 'IRD Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Business identifier.',
      },
      {
        value: 'gst_number',
        label: 'GST Number',
        placeholder: 'GST Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Required for invoices.',
      },
    ],
  },

  {
    country_code: 'DE',
    country_name: 'Germany',
    taxConfig: {
      currency: 'EUR',
      hasVat: true,
      vatRate: 19,
    },
    fields: [
      {
        value: 'vat_number',
        label: 'VAT Number',
        placeholder: 'DE VAT Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Required for tax invoice.',
      },
      {
        value: 'tax_number',
        label: 'Tax Number',
        placeholder: 'Steuernummer',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'German tax office number.',
      },
    ],
  },

  {
    country_code: 'FR',
    country_name: 'France',
    taxConfig: {
      currency: 'EUR',
      hasVat: true,
      vatRate: 20,
    },
    fields: [
      {
        value: 'vat_number',
        label: 'VAT Number',
        placeholder: 'FR VAT Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Required for invoices.',
      },
      {
        value: 'siret',
        label: 'SIRET',
        placeholder: 'SIRET Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Business registration.',
      },
    ],
  },
  {
    country_code: 'SA',
    country_name: 'Saudi Arabia',
    taxConfig: {
      currency: 'SAR',
      hasVat: true,
      vatRate: 15,
    },
    fields: [
      {
        value: 'vat_number',
        label: 'VAT Number',
        placeholder: '15-digit VAT Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Mandatory for VAT invoices.',
      },
      {
        value: 'cr_number',
        label: 'Commercial Registration',
        placeholder: 'CR Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Business registration.',
      },
    ],
  },

  {
    country_code: 'KW',
    country_name: 'Kuwait',
    taxConfig: {
      currency: 'KWD',
    },
    fields: [
      {
        value: 'civil_id',
        label: 'Civil ID / Tax ID',
        placeholder: 'Civil ID',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: true,
        helperText: 'Required for company registration.',
      },
    ],
  },

  {
    country_code: 'QA',
    country_name: 'Qatar',
    taxConfig: {
      currency: 'QAR',
    },
    fields: [
      {
        value: 'tax_card',
        label: 'Tax Card Number',
        placeholder: 'Tax Card',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: true,
        helperText: 'Business tax ID.',
      },
    ],
  },

  {
    country_code: 'OM',
    country_name: 'Oman',
    taxConfig: {
      currency: 'OMR',
      hasVat: true,
      vatRate: 5,
    },
    fields: [
      {
        value: 'vat_number',
        label: 'VAT Number',
        placeholder: 'VAT Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Required for VAT.',
      },
    ],
  },

  {
    country_code: 'BH',
    country_name: 'Bahrain',
    taxConfig: {
      currency: 'BHD',
      hasVat: true,
      vatRate: 10,
    },
    fields: [
      {
        value: 'vat_number',
        label: 'VAT Number',
        placeholder: 'VAT Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Mandatory.',
      },
    ],
  },

  {
    country_code: 'CN',
    country_name: 'China',
    taxConfig: {
      currency: 'CNY',
      hasVat: true,
      vatRate: 13,
    },
    fields: [
      {
        value: 'unified_social_credit_code',
        label: 'Unified Social Credit Code',
        placeholder: '18-digit code',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Business registration + tax ID.',
      },
    ],
  },

  {
    country_code: 'JP',
    country_name: 'Japan',
    taxConfig: {
      currency: 'JPY',
      hasVat: true,
      vatRate: 10,
    },
    fields: [
      {
        value: 'corporate_number',
        label: 'Corporate Number',
        placeholder: '13-digit number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Legal entity registration.',
      },
      {
        value: 'invoice_registration',
        label: 'Invoice Registration Number',
        placeholder: 'T1234567890123',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Consumption tax invoice.',
      },
    ],
  },

  {
    country_code: 'SG',
    country_name: 'Singapore',
    taxConfig: {
      currency: 'SGD',
      hasVat: true,
      vatRate: 9,
    },
    fields: [
      {
        value: 'uen',
        label: 'UEN',
        placeholder: 'Unique Entity Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Business identifier.',
      },
      {
        value: 'gst_registration',
        label: 'GST Registration',
        placeholder: 'GST Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'GST billing.',
      },
    ],
  },

  {
    country_code: 'US',
    country_name: 'United States',
    taxConfig: {
      currency: 'USD',
      hasStateTax: true,
    },
    fields: [
      {
        value: 'ein',
        label: 'EIN',
        placeholder: 'Employer Identification Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: true,
        helperText: 'Federal tax ID.',
      },
      {
        value: 'sales_tax_permit',
        label: 'Sales Tax Permit',
        placeholder: 'Permit Number',
        required: false,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: false,
        helperText: 'Required depending on state.',
      },
    ],
  },

  {
    country_code: 'CA',
    country_name: 'Canada',
    taxConfig: {
      currency: 'CAD',
      hasVat: true,
    },
    fields: [
      {
        value: 'business_number',
        label: 'Business Number',
        placeholder: 'BN',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'CRA business number.',
      },
      {
        value: 'gst_hst',
        label: 'GST/HST Number',
        placeholder: 'GST/HST',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Tax invoice.',
      },
    ],
  },

  {
    country_code: 'BR',
    country_name: 'Brazil',
    taxConfig: {
      currency: 'BRL',
      hasVat: true,
    },
    fields: [
      {
        value: 'cnpj',
        label: 'CNPJ',
        placeholder: 'Company Tax ID',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Business registration.',
      },
    ],
  },

  {
    country_code: 'MX',
    country_name: 'Mexico',
    taxConfig: {
      currency: 'MXN',
      hasVat: true,
      vatRate: 16,
    },
    fields: [
      {
        value: 'rfc',
        label: 'RFC',
        placeholder: 'Tax ID',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'SAT tax ID.',
      },
    ],
  },

  {
    country_code: 'HK',
    country_name: 'Hong Kong',
    taxConfig: {
      currency: 'HKD',
    },
    fields: [
      {
        value: 'business_registration',
        label: 'Business Registration Number',
        placeholder: 'BR Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: true,
        helperText: 'Required for business.',
      },
    ],
  },

  {
    country_code: 'MY',
    country_name: 'Malaysia',
    taxConfig: {
      currency: 'MYR',
      hasVat: true,
      vatRate: 8,
    },
    fields: [
      {
        value: 'ssm',
        label: 'SSM Registration',
        placeholder: 'Business Registration',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Business registration.',
      },
      {
        value: 'sst_number',
        label: 'SST Number',
        placeholder: 'Sales Tax Registration',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Tax billing.',
      },
    ],
  },
  {
    country_code: 'TH',
    country_name: 'Thailand',
    taxConfig: {
      currency: 'THB',
      hasVat: true,
      vatRate: 7,
    },
    fields: [
      {
        value: 'tax_id',
        label: 'Tax ID',
        placeholder: '13-digit Tax ID',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Required for invoice and VAT.',
      },
      {
        value: 'vat_registration',
        label: 'VAT Registration Number',
        placeholder: 'VAT Registration',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: false,
        helperText: 'Displayed on tax invoice.',
      },
    ],
  },

  {
    country_code: 'ID',
    country_name: 'Indonesia',
    taxConfig: {
      currency: 'IDR',
      hasVat: true,
      vatRate: 11,
    },
    fields: [
      {
        value: 'npwp',
        label: 'NPWP',
        placeholder: 'Taxpayer Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Mandatory for business tax.',
      },
      {
        value: 'nib',
        label: 'Business License (NIB)',
        placeholder: 'NIB Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Required for commerce.',
      },
    ],
  },

  {
    country_code: 'PH',
    country_name: 'Philippines',
    taxConfig: {
      currency: 'PHP',
      hasVat: true,
      vatRate: 12,
    },
    fields: [
      {
        value: 'tin',
        label: 'TIN',
        placeholder: 'Taxpayer Identification Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Mandatory on invoice.',
      },
      {
        value: 'bir_registration',
        label: 'BIR Registration',
        placeholder: 'BIR Certificate',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Required for business.',
      },
    ],
  },

  {
    country_code: 'KR',
    country_name: 'South Korea',
    taxConfig: {
      currency: 'KRW',
      hasVat: true,
      vatRate: 10,
    },
    fields: [
      {
        value: 'business_reg_no',
        label: 'Business Registration Number',
        placeholder: '10-digit number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Required for invoicing.',
      },
      {
        value: 'vat_number',
        label: 'VAT Number',
        placeholder: 'VAT Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Required for tax invoice.',
      },
    ],
  },

  {
    country_code: 'AR',
    country_name: 'Argentina',
    taxConfig: {
      currency: 'ARS',
      hasVat: true,
      vatRate: 21,
    },
    fields: [
      {
        value: 'cuit',
        label: 'CUIT',
        placeholder: 'CUIT',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Business tax ID.',
      },
      {
        value: 'vat_reg',
        label: 'VAT Registration',
        placeholder: 'VAT',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: false,
        helperText: 'Required for tax invoice.',
      },
    ],
  },

  {
    country_code: 'CO',
    country_name: 'Colombia',
    taxConfig: {
      currency: 'COP',
      hasVat: true,
      vatRate: 19,
    },
    fields: [
      {
        value: 'nit',
        label: 'NIT',
        placeholder: 'Tax Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Required for tax.',
      },
      {
        value: 'rut',
        label: 'RUT',
        placeholder: 'Business registration',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Required for legal selling.',
      },
    ],
  },

  {
    country_code: 'CL',
    country_name: 'Chile',
    taxConfig: {
      currency: 'CLP',
      hasVat: true,
      vatRate: 19,
    },
    fields: [
      {
        value: 'rut',
        label: 'RUT',
        placeholder: 'Tax ID',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Mandatory.',
      },
    ],
  },

  {
    country_code: 'PE',
    country_name: 'Peru',
    taxConfig: {
      currency: 'PEN',
      hasVat: true,
      vatRate: 18,
    },
    fields: [
      {
        value: 'ruc',
        label: 'RUC',
        placeholder: '11-digit number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Business tax ID.',
      },
    ],
  },

  {
    country_code: 'IT',
    country_name: 'Italy',
    taxConfig: {
      currency: 'EUR',
      hasVat: true,
      vatRate: 22,
    },
    fields: [
      {
        value: 'vat_number',
        label: 'VAT Number',
        placeholder: 'Partita IVA',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Required for invoice.',
      },
      {
        value: 'rea',
        label: 'REA',
        placeholder: 'REA Registration',
        required: false,
        requiredForSelling: false,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Optional chamber registration.',
      },
    ],
  },

  {
    country_code: 'ES',
    country_name: 'Spain',
    taxConfig: {
      currency: 'EUR',
      hasVat: true,
      vatRate: 21,
    },
    fields: [
      {
        value: 'nif_cif',
        label: 'NIF / CIF',
        placeholder: 'Tax Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Required for invoice.',
      },
      {
        value: 'vat_number',
        label: 'VAT Number',
        placeholder: 'ES VAT',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: false,
        helperText: 'EU VAT.',
      },
    ],
  },

  {
    country_code: 'NL',
    country_name: 'Netherlands',
    taxConfig: {
      currency: 'EUR',
      hasVat: true,
      vatRate: 21,
    },
    fields: [
      {
        value: 'kvk',
        label: 'KvK Number',
        placeholder: 'Chamber of Commerce',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Business registration.',
      },
      {
        value: 'vat_number',
        label: 'VAT Number',
        placeholder: 'NL VAT',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Tax invoice.',
      },
    ],
  },

  {
    country_code: 'FJ',
    country_name: 'Fiji',
    taxConfig: {
      currency: 'FJD',
      hasVat: true,
      vatRate: 15,
    },
    fields: [
      {
        value: 'tin',
        label: 'TIN',
        placeholder: 'Tax Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Required for invoices.',
      },
    ],
  },

  {
    country_code: 'PG',
    country_name: 'Papua New Guinea',
    taxConfig: {
      currency: 'PGK',
      hasVat: true,
      vatRate: 10,
    },
    fields: [
      {
        value: 'tin',
        label: 'TIN',
        placeholder: 'Taxpayer Number',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: true,
        is_primary_tax_id: true,
        helperText: 'Mandatory for business.',
      },
      {
        value: 'ipa_registration',
        label: 'IPA Registration',
        placeholder: 'Business Registration',
        required: true,
        requiredForSelling: true,
        showOnInvoice: true,
        editableAtCheckout: false,
        affectsTaxCalculation: false,
        is_primary_tax_id: false,
        helperText: 'Company registration.',
      },
    ],
  },
];
